### ISSUE TITLE
imaplib.error: command STORE illegal in state LOGOUT, only allowed in states SELECTED

### ISSUE THREAD

**Issue by TerryLansdown** [joolswhitehorn/stuff-projects#3]
Hi,

Enjoying trying to get this to work, but the script is failing for me on 'imaplib.error: command STORE illegal in state LOGOUT, only allowed in states SELECTED'

Any ideas? Thanks for your efforts on this. Output is:
```
Current temp
22.937
Target temp
Traceback (most recent call last):
  File "pinest.py", line 85, in <module>
    print read_gmail()
  File "pinest.py", line 74, in read_gmail
    mail.store(num, '+FLAGS', '\\Deleted')
  File "/usr/lib/python2.7/imaplib.py", line 721, in store
    typ, dat = self._simple_command('STORE', message_set, command, flags)
  File "/usr/lib/python2.7/imaplib.py", line 1070, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "/usr/lib/python2.7/imaplib.py", line 825, in _command
    ', '.join(Commands[name])))
imaplib.error: command STORE illegal in state LOGOUT, only allowed in states SELECTED
```

**Comment by Alex-Beaven** [comment]
There's bad indenting in the for loop at the end of read_gmail() function. It closes the mail object in the first iteration of the loop. 


This is it fixed:


![image](https://user-images.githubusercontent.com/35688353/35767955-021954d8-08ed-11e8-9cbf-1d91f7215183.png)

**Comment by thermrpi9** [comment]
Hi, i've tried the program but it gives me a imaplib error : command SELECT illegal in state NONAUTH, only allowed in states AUTH, SELECTED. I'm not good at python i really don't know how to fix it.

**Comment by TerryLansdown** [comment]
Great, thanks!
